; PlatformIO Project Configuration File
; greenie-auto — Dự án đo độ ẩm với c

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Tốc độ Serial Monitor
monitor_speed = 115200

; Upload port (set your ESP32 serial port, e.g. COM3, COM4)
upload_port = COM4

; Thư viện cần thiết
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
